### ISSUE TITLE
The ST is not a Cycle GAN

### ISSUE THREAD

**Issue by EnzoWuu** [TAMU-VITA/AGD#13]
I don't find the cycle loss. Is it  a improved pix2pix model ?

**Comment by tilmto** [comment]
We use the CycleGAN model as the target to be compressed and evaluate on the unpaired image translation tasks. Since we use a distillation loss with a pretrained heavy generator (CycleGAN's generator), the cycle consistency loss is no more necessary here. From this perspective, its training scheme is similar with pix2pix. You can refer to Eq.(3) in our paper for our objective function design.
